---
# -- Number of connector instances
replicaCount: 1

image:
  # -- Connector image name
  repository: ghcr.io/international-data-spaces-association/dataspace-connector
  # -- Image pull policy
  pullPolicy: Always
  # -- Connector version without the "v"
  tag: ""

# -- Connector properties
env:
  # -- Connector environment variables
  config:
    # -- Path to the connector configuration
    CONFIGURATION_PATH: "/etc/dataspace-connector/config.json"
    # -- Whether TLS is enabled
    SERVER_SSL_ENABLED: "false"
    # -- SSL keystore location
    SERVER_SSL_KEY-STORE: "/var/run/certs/keystore.p12"
    # -- Connector logging configuration location
    LOGGING_CONFIG: "file:///etc/dataspace-connector/log4j2.xml"
    # -- Actuactor endpoints to expose
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "metrics,health"
    # -- Whether to enable metrics actuactor
    MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
    # -- Whether to enable health actuactor
    MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
  # -- Connector secrets
  secrets:
    # -- Connector admin username
    SPRING_SECURITY_USER_NAME: "admin"
    # -- Connector admin password
    SPRING_SECURITY_USER_PASSWORD: "password"
  flyway:
    SPRING_FLYWAY_ENABLED: "false"
    SPRING_FLYWAY_BASELINE-ON-MIGRATE: "false"
    SPRING_FLYWAY_BASELINE-VERSION: "8.0.2"
    SPRING_JPA_HIBERNATE_DDL-AUTO: "update"

# -- Persistent database properties
postgresql:
  # -- Whether to use a postgresql backend
  enabled: true
  # -- Postgresql username
  postgresqlUsername: "password"
  # -- Postgresql password
  postgresqlPassword: "username"
  # -- Postgresql database name
  postgresqlDatabase: "test"
  # -- Kubernetes postgresql service
  service:
    # -- Postgresql service port
    port: "5432"

# -- Secrets for pulling images
imagePullSecrets: []

# -- Kubernetes service account for the connector
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: null

# -- Annotation for the deployed pods
podAnnotations: {}

# -- Security context for the pods
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# -- Security context applied to the pods
securityContext:
  # -- Whether to allow privilege escalations
  allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true Will make tomcat crash
  # -- User running the pods
  runAsUser: 65532
  # -- Capabilities of the pods
  capabilities:
    drop:
      - ALL

# -- Kubernetes connector service settings
service:
  # -- Connector service type
  type: ClusterIP
  # -- Connector service port
  port: 80

# -- Connector kubernetes ingress settings
ingress:
  # -- Whether to enable ingress for the connector
  enabled: false
  className: ""
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "localhost"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: testsecret-tls
      hosts:
        - localhost

# -- Connector kubernetes resource settings
resources:
  limits:
    cpu: "8"
    memory: "4Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

# -- Connector horizontal autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
